insert into team (name) values ("4A INF");
insert into team (name) values ("4B INF");
insert into team (name) values ("1A GRA");
insert into team (name) values ("2AB INF");
insert into task (team, data) values ("4B INF", "2016-01-01 11:00:00");
insert into student (name, team) values ("Basso Andrea", "4B INF");
insert into student (name, team) values ("Basso Matteo", "4B INF");
insert into student (name, team) values ("Ben Khalifa Youssef ", "4B INF");
insert into student (name, team) values ("Bertazzon Alice ", "4B INF");
insert into student (name, team) values ("Bianchin Alessandro ", "4B INF");
insert into student (name, team) values ("Bordin Gianpaolo ", "4B INF");
insert into student (name, team) values ("Bortolamiol Alessandro ", "4B INF");
insert into student (name, team) values ("Crema Luca ", "4B INF");
insert into student (name, team) values ("Demian Oleksandr ", "4B INF");
insert into student (name, team) values ("Fedato Davide ", "4B INF");
insert into student (name, team) values ("Franceschin Nicolò", "4B INF");
insert into student (name, team) values ("Gallina Greta ", "4B INF");
insert into student (name, team) values ("Gastaldo Samuele", "4B INF");
insert into student (name, team) values ("Grando Giacomo ", "4B INF");
insert into student (name, team) values ("Kawkab Wassim ", "4B INF");
insert into student (name, team) values ("Menegon Diego ", "4B INF");
insert into student (name, team) values ("Nardi Davide ", "4B INF");
insert into student (name, team) values ("Pellizzari Giacomo", "4B INF");
insert into student (name, team) values ("Rotaru Roxana ", "4B INF");
insert into student (name, team) values ("Torresan Federico ", "4B INF");
insert into student (name, team) values ("Zandonà Nicola", "4B INF");
insert into student (name, team) values ("Zanella Igor ", "4B INF");
insert into student (name, team) values ("Zhiqiang Zhou", "4B INF");